name: Run Java Maven Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Navigate to Java folder
        run: cd Java

      - name: Build and Run Tests
        run: mvn clean test -f ./java/pom.xml

      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report -f ./java/pom.xml

      - name: Upload JaCoCo Report (Code Coverage)
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: java/target/site/jacoco/

      - name: Upload Surefire Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: java/target/surefire-reports/

      - name: Display Test Results in Logs
        if: always()
        run: cat java/target/surefire-reports/*.txt || true
