name: Run Java Maven Tests

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        queue: [LinkedIntQueue, ArrayIntQueue]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # ✅ Use the latest OpenJDK distribution
          java-version: '21'        # ✅ Java 21 version

      - name: Run Maven Tests
        working-directory: ./Java   # ✅ Your pom.xml is in java/ folder
        run: mvn test -Dtest=IntQueueTest -Dqueue=${{ matrix.queue }}
